name: pre-commit

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          echo ${{ github.event.pull_request.head.repo.full_name }}
          echo ${{ github.event.pull_request.head.ref }}
      - name: Dump Github Context
        run: |
          echo "mari kita coba pull" > context-${{ github.sha }}.json
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto_commit
        if: always()
      - name: Approve pull request
        if: steps.auto_commit.conclusion == 'failure'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: REQUEST_CHANGES
          body: 'Thank you dependabot 🎊'