name: pre-commit-2

on:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dump Github Context
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_CONTEXT > context-${{ github.sha }}.json

      - uses: EndBug/add-and-commit@v9
        if: always()
        id: commit_changes
        with:
          message: \[pre-commit\] auto update
